android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java
Use String.valueOf(targetDirectory) instead of targetDirectory directly in compare
=> string value of targetDirectory instead of ref

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java
=> Fix #62 - NullPointerException in boolean comparison on reset() where toAutoUpdate is not provided

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java
=> fix(android): Fix typo in 'getPluginVersion'

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java, android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java, android/src/main/java/ee/forgr/capacitor_updater/VersionInfo.java
Safe to merge. Fully tested on Android.
=> chore(android): refactor VersionInfo to use single json data store

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java
This was probably written in Swift and copied over.
=> fix(android): use this not self in java, fix build

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java, android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java, ios/Plugin/CapacitorUpdater.swift
Reverse if condition on _checkCancelDelay function in android
Reverse if condition on onActivityStarted function in android
=> fix _checkCancelDelay android bug, and other minor changes

ios/Plugin/CapacitorUpdaterPlugin.swift
Fix the issue on already deleted bundle
=> fix ios double kill

README.md, ios/Plugin/BundleInfo.swift, ios/Plugin/BundleStatus.swift, ios/Plugin/CapacitorUpdater.swift, ios/Plugin/CapacitorUpdaterPlugin.swift, src/definitions.ts, src/web.ts
Hi @riderx 
I have fixed few of the issues as part of #163 
Would it require to merge these into master so that the updated list of issues start reflecting on sonarcloud server after my changes?
=> Issue 163 fix sonarcloud issues

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java
Hi I had about 4 hours trying to test Capgo, I thought I had something wrong in my configuration. After testing for hours and reading the documentation I set out to debug the plugin code and realized that the autoupdate validation was wrong.
Great job, I love your project.
=> fix: autoupdate without livereload mode

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java, android/src/main/java/ee/forgr/capacitor_updater/DownloadService.java
I was experiencing a stream leak in some scenarios, so I tightened up the resource disposal. This update is working successfully here.
=> More robust disposal of streams

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java, ios/Plugin/CapacitorUpdaterPlugin.swift, src/definitions.ts
=> fix delay kill

ios/Plugin/CapacitorUpdaterPlugin.swift
Part 1 that closes https://github.com/Cap-go/capacitor-updater/issues/72 so I can /claim #72
=> fix(ios): set error flag to false for non-error actions

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java
@riderx I've fixed this wrong condition in Android. without fixing it, I was unable to download new bundles
=> fix: wrong condition

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java
=> fix android 14

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java
This PR fixes a new bug on Android 14
=> possibly fix android 14 crash

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java
Fixes https://github.com/Cap-go/capacitor-updater/issues/336
=> 🐛 (fix): Fix a race condition in checkForUpdateAfterDelay

android/src/main/java/ee/forgr/capacitor_updater/DownloadService.java
Fix this issue (https://github.com/Cap-go/capacitor-updater/issues/369)
=> fix: updates on Android 14 (SDK 34)

android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java
=> Attempt to fix #410

ios/Plugin/CapacitorUpdater.swift
This PR addresses an issue that was previously mentioned but overlooked in #400. It ensures that every 10% milestone is correctly notified when downloading an update on iOS.
=> adding milestones for notifying download on ios

CHANGELOG.md, android/build.gradle, android/src/main/AndroidManifest.xml, android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java, android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java, android/src/main/java/ee/forgr/capacitor_updater/DownloadService.java, android/src/main/java/ee/forgr/capacitor_updater/DownloadWorkerManager.java, ios/Plugin/CapacitorUpdaterPlugin.swift, package.json
You can test it in `6.7.7-alpha.2`
=> Development fix issue with foreground service

README.md, android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdater.java, android/src/main/java/ee/forgr/capacitor_updater/CapacitorUpdaterPlugin.java, ios/Plugin/CapacitorUpdater.swift, ios/Plugin/CapacitorUpdaterPlugin.swift, src/definitions.ts
This fixes #518 
I use this PR as so:
```ts
const bundles = await CapacitorUpdater.list({raw: true})
for (const bundle of bundles.bundles) {
await CapacitorUpdater.delete({id: bundle.id }).catch(e => {
// ignore error
console.error(e)
})
}
```
=> feat: list({raw: true}) + better delete()
